name: glassy_bubble
description: A stunning glassy bubble widget for Flutter with custom gradients, blur effects, and interactive scale animations.
version: 0.0.3
repository: https://github.com/dyuta6/glassy_bubble
issue_tracker: https://github.com/dyuta6/glassy_bubble/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
